/** Notification categories for filtering & preferences */
export const NOTIFICATION_CATEGORIES = [
  "SOCIAL",
  "MATRIMONY",
  "MESSAGES",
  "COMMUNITY",
  "SYSTEM"
] as const;

export type NotificationCategory = (typeof NOTIFICATION_CATEGORIES)[number];

export const NOTIFICATION_TYPES = {
  // Social
  POST_LIKE: "POST_LIKE",
  POST_COMMENT: "POST_COMMENT",
  COMMENT_REPLY: "COMMENT_REPLY",
  POST_MENTION: "POST_MENTION",
  POST_SHARE: "POST_SHARE",
  USER_FOLLOW: "USER_FOLLOW",
  // Matrimony
  MATRIMONY_INTEREST_RECEIVED: "MATRIMONY_INTEREST_RECEIVED",
  MATRIMONY_INTEREST_ACCEPTED: "MATRIMONY_INTEREST_ACCEPTED",
  MATRIMONY_INTEREST_DECLINED: "MATRIMONY_INTEREST_DECLINED",
  MATRIMONY_MATCH: "MATRIMONY_MATCH",
  MATRIMONY_PROFILE_APPROVED: "MATRIMONY_PROFILE_APPROVED",
  MATRIMONY_PROFILE_REJECTED: "MATRIMONY_PROFILE_REJECTED",
  MATRIMONY_CHANGES_REQUESTED: "MATRIMONY_CHANGES_REQUESTED",
  MATRIMONY_PROFILE_VIEWED: "MATRIMONY_PROFILE_VIEWED",
  MATRIMONY_PREMIUM_EXPIRING: "MATRIMONY_PREMIUM_EXPIRING",
  MATRIMONY_PAYMENT_SUCCESS: "MATRIMONY_PAYMENT_SUCCESS",
  MATRIMONY_PAYMENT_FAILED: "MATRIMONY_PAYMENT_FAILED",
  MATRIMONY_SUBSCRIPTION_ACTIVATED: "MATRIMONY_SUBSCRIPTION_ACTIVATED",
  MATRIMONY_SUBSCRIPTION_EXPIRED: "MATRIMONY_SUBSCRIPTION_EXPIRED",
  MATRIMONY_HOROSCOPE_REQUEST: "MATRIMONY_HOROSCOPE_REQUEST",
  MATRIMONY_HOROSCOPE_SHARED: "MATRIMONY_HOROSCOPE_SHARED",
  MATRIMONY_APPLICATION_SUBMITTED: "MATRIMONY_APPLICATION_SUBMITTED",
  MATRIMONY_CONTACT_UNLOCKED: "MATRIMONY_CONTACT_UNLOCKED",
  // Messages
  MESSAGE_NEW: "MESSAGE_NEW",
  MESSAGE_REQUEST: "MESSAGE_REQUEST",
  MESSAGE_MEDIA: "MESSAGE_MEDIA",
  // Admin / account
  ACCOUNT_VERIFIED: "ACCOUNT_VERIFIED",
  ACCOUNT_REJECTED: "ACCOUNT_REJECTED",
  ACCOUNT_REVIEW: "ACCOUNT_REVIEW",
  // Community
  COMMUNITY_ANNOUNCEMENT: "COMMUNITY_ANNOUNCEMENT",
  COMMUNITY_EVENT: "COMMUNITY_EVENT",
  COMMUNITY_UPDATE: "COMMUNITY_UPDATE",
  // System
  SYSTEM_GENERIC: "SYSTEM_GENERIC",
  ADMIN_BROADCAST: "ADMIN_BROADCAST"
} as const;

export type NotificationType = (typeof NOTIFICATION_TYPES)[keyof typeof NOTIFICATION_TYPES];

export const NOTIFICATION_ACTIONS = {
  OPEN_POST: "OPEN_POST",
  OPEN_POST_COMMENT: "OPEN_POST_COMMENT",
  OPEN_CHAT: "OPEN_CHAT",
  OPEN_MATRIMONY_HOME: "OPEN_MATRIMONY_HOME",
  OPEN_MATRIMONY_INTERESTS: "OPEN_MATRIMONY_INTERESTS",
  OPEN_MATRIMONY_MATCHES: "OPEN_MATRIMONY_MATCHES",
  OPEN_MATRIMONY_CANDIDATE: "OPEN_MATRIMONY_CANDIDATE",
  OPEN_MATRIMONY_SETUP: "OPEN_MATRIMONY_SETUP",
  OPEN_MATRIMONY_PLANS: "OPEN_MATRIMONY_PLANS",
  OPEN_MATRIMONY_MY_SUBSCRIPTION: "OPEN_MATRIMONY_MY_SUBSCRIPTION",
  OPEN_MATRIMONY_VIEWS: "OPEN_MATRIMONY_VIEWS",
  OPEN_MESSAGES: "OPEN_MESSAGES",
  OPEN_NOTIFICATIONS: "OPEN_NOTIFICATIONS",
  NONE: "NONE"
} as const;

export type NotificationActionType = (typeof NOTIFICATION_ACTIONS)[keyof typeof NOTIFICATION_ACTIONS];

export const CATEGORY_BY_TYPE: Record<NotificationType, NotificationCategory> = {
  POST_LIKE: "SOCIAL",
  POST_COMMENT: "SOCIAL",
  COMMENT_REPLY: "SOCIAL",
  POST_MENTION: "SOCIAL",
  POST_SHARE: "SOCIAL",
  USER_FOLLOW: "SOCIAL",
  MATRIMONY_INTEREST_RECEIVED: "MATRIMONY",
  MATRIMONY_INTEREST_ACCEPTED: "MATRIMONY",
  MATRIMONY_INTEREST_DECLINED: "MATRIMONY",
  MATRIMONY_MATCH: "MATRIMONY",
  MATRIMONY_PROFILE_APPROVED: "MATRIMONY",
  MATRIMONY_PROFILE_REJECTED: "MATRIMONY",
  MATRIMONY_CHANGES_REQUESTED: "MATRIMONY",
  MATRIMONY_PROFILE_VIEWED: "MATRIMONY",
  MATRIMONY_PREMIUM_EXPIRING: "MATRIMONY",
  MATRIMONY_PAYMENT_SUCCESS: "MATRIMONY",
  MATRIMONY_PAYMENT_FAILED: "MATRIMONY",
  MATRIMONY_SUBSCRIPTION_ACTIVATED: "MATRIMONY",
  MATRIMONY_SUBSCRIPTION_EXPIRED: "MATRIMONY",
  MATRIMONY_HOROSCOPE_REQUEST: "MATRIMONY",
  MATRIMONY_HOROSCOPE_SHARED: "MATRIMONY",
  MATRIMONY_APPLICATION_SUBMITTED: "MATRIMONY",
  MATRIMONY_CONTACT_UNLOCKED: "MATRIMONY",
  MESSAGE_NEW: "MESSAGES",
  MESSAGE_REQUEST: "MESSAGES",
  MESSAGE_MEDIA: "MESSAGES",
  ACCOUNT_VERIFIED: "SYSTEM",
  ACCOUNT_REJECTED: "SYSTEM",
  ACCOUNT_REVIEW: "SYSTEM",
  COMMUNITY_ANNOUNCEMENT: "COMMUNITY",
  COMMUNITY_EVENT: "COMMUNITY",
  COMMUNITY_UPDATE: "COMMUNITY",
  SYSTEM_GENERIC: "SYSTEM",
  ADMIN_BROADCAST: "COMMUNITY"
};

export const MATRIMONY_NOTIFICATION_TYPES = new Set<NotificationType>(
  Object.entries(CATEGORY_BY_TYPE)
    .filter(([, c]) => c === "MATRIMONY")
    .map(([t]) => t as NotificationType)
);

export const GROUPABLE_TYPES = new Set<NotificationType>([
  NOTIFICATION_TYPES.POST_LIKE,
  NOTIFICATION_TYPES.POST_COMMENT,
  NOTIFICATION_TYPES.COMMENT_REPLY,
  NOTIFICATION_TYPES.MATRIMONY_PROFILE_VIEWED
]);

export const PREFERENCE_KEY_BY_CATEGORY: Record<NotificationCategory, string> = {
  SOCIAL: "socialEnabled",
  MATRIMONY: "matrimonyEnabled",
  MESSAGES: "messagesEnabled",
  COMMUNITY: "communityEnabled",
  SYSTEM: "systemEnabled"
};
